version: '3'

services:
  jira:
    image: mafrosis/jira:dev
    build:
      context: .
    volumes:
      - ./:/app
      - ./config:/root/.config/jira-cli
      - /app/.git
      - /app/jira_cli.egg-info
