version: '3'

services:
  jiracli:
    image: mafrosis/jiracli
    build:
      context: .
    volumes:
      - ./jira_cli:/app/jira_cli
      - ./test:/app/test
      - ./config:/root/.config/jiracli

  test:
    image: mafrosis/jiracli-test
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./jira_cli:/app/jira_cli
      - ./test:/app/test
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
      - ./pytest.ini:/app/pytest.ini
      - ./.pylintrc:/app/.pylintrc

  jira:
    image: mafrosis/jira
    build:
      context: .
      dockerfile: Dockerfile.jira
      args:
        USER_ID: 1000
        GROUP_ID: 1004
    ports:
      - 8666:8080
    volumes:
      - ./jira_data:/var/atlassian/application-data/jira
    environment:
      ATL_DB_DRIVER: org.postgresql.Driver
      ATL_JDBC_USER: postgres
      ATL_JDBC_PASSWORD: postgres
      ATL_DB_TYPE: postgres72
      ATL_JDBC_URL: jdbc:postgresql://postgres:5432/jira
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6-alpine
    ports:
      - 40699:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jira
      LANG: POSIX.UTF-8

volumes:
  postgres_data: {}
