name: Build-Test-Publish
on:
- push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build for python ${{ matrix.python-version }}
      run: |
        docker-compose build --build-arg PYTHON_VERSION=${{ matrix.python-version }} jira-offline
        docker-compose build test

    - name: Extra build step for python 3.6 (include dataclasses & typing from pypi)
      if: matrix.python-version < 3.7
      run: |
        # Build an updated Docker image including dataclasses lib
        tee Dockerfile.36 > /dev/null <<EOF
        FROM mafrosis/jira-offline-test
        RUN pip install dataclasses typing
        EOF
        docker build -f Dockerfile.36 -t mafrosis/jira-offline-test .

    - name: Lint with pylint
      run: |
        make lint

    - name: Typecheck with mypy
      run: |
        make typecheck

    - name: Test with pytest
      run: |
        make test

    - name: Publish dev docker image
      if: matrix.python-version == 3.7 && github.ref == 'refs/heads/master'
      run: |
        echo "$GITHUB_TOKEN" | docker login -u mafrosis --password-stdin docker.pkg.github.com
        docker tag mafrosis/jira-offline docker.pkg.github.com/mafrosis/jira-offline/jira-offline:dev
        docker push docker.pkg.github.com/mafrosis/jira-offline/jira-offline:dev
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
