name: build
on:
  push:
    branches:
      - '*'
      - '!wip*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build for python ${{ matrix.python-version }}
      run: |
        docker-compose build --build-arg PYTHON_VERSION=${{ matrix.python-version }} jira-offline
        docker-compose build test

    - name: Lint with pylint
      run: |
        make lint

    - name: Typecheck with mypy
      run: |
        make typecheck

    - name: Test with pytest
      run: |
        make test

    - name: Publish dev docker image
      if: matrix.python-version == 3.7 && github.ref == 'refs/heads/master'
      run: |
        make publish-docker
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: dev
